### ISSUE TITLE
keyでファイルタイプのリストを使いたい

### ISSUE THREAD

**Issue by uplus** [syngan/vim-clurin#10]
下記の用に複数のファイルタイプで共通の設定と独自の設定をg:clurinのみで定義したいです。

```vim
let g:clurin = {
      \ ['sh','zsh']: {'def': [
      \   ['if', 'elif', 'else'],
      \ ]},
      \ 'zsh': {'def': [
      \   ['chpwd', 'periodic', 'precmd', 'preexec',],	
      \ ]}
      \ }
```

今のところは個別の設定をg:clurinで、共通の設定をautocmdでb:clurinに定義しています。
vim-clurinはswitchなどと比べautocmdを使わないでファイルタイプ毎の設定ができるのが利点なので、b:clurinを極力使わずに済ませたいです。

**Comment by uplus** [comment]
文法的にリストをキーには出来ない事を忘れてました。
キーをリスト風にするなら、コンマかドット、スペース区切りの文字列でしょうか。

**Comment by syngan** [comment]
- 検索順序が定義できないので仕様として不十分
- 以下で十分では?

```
let c = ['if', 'else', '...]
let g:clurin = {....}
let g:clurin.zsh.def += c
let g:clurin.sh.def += c
```
