### ISSUE TITLE
Case sensitive switching is not working. ex: o:True -> False. x: True -> FALSE

### ISSUE THREAD

**Issue by lamsh** [syngan/vim-clurin#7]
切替時に大文字小文字がうまく判別されていないようです。

例えば、以下のように大文字小文字に応じて切り替えることを目的とします。
True -> False
TRUE -> FALSE

これを実現するために、.vimrcに以下を設定しました。

```
  nmap + <Plug>(clurin-next)
  nmap - <Plug>(clurin-prev)
  vmap + <Plug>(clurin-next)
  vmap - <Plug>(clurin-prev)
  function! g:default_pm(cnt) abort
    if a:cnt >= 0
      execute 'normal!'   a:cnt  . "j0"
    else
      execute 'normal!' (-a:cnt) . "k0"
    endif
  endfunction
  let g:clurin = {
  \   '-': {
  \     'nomatch': function('g:default_pm'),
  \     'def': [
  \       ['TRUE', 'FALSE'],
  \       ['True', 'False'],
  \     ]
  \   }
  \ }
```

この状態で、`True'の上で'-'か'+'を押下すると、'FALSE'になってしまいます。

正規表現で対応しようと以下の設定を試しました。

```
  let g:clurin = {             
  \   '-': {                   
  \     'nomatch': function('g:default_pm'),
  \     'def': [               
  \       [
  \         {'pattern': 'True', 'replace': 'False'},
  \         {'pattern': 'False', 'replace': 'True'},
  \         {'pattern': 'TRUE', 'replace': 'FALSE'},
  \         {'pattern': 'FALSE', 'replace': 'TRUE'},
  \       ]
  \     ]                                                                       
  \   }     
  \ }
```

この状態で、`True'の上で'+'を押下すると、反応がなく、'-'を押下すると、'TRUE'になってしまいます。
また、'TRUE'の上で、'-'を押下すると、反応がなく、'+'を押下すると、'True'になりました。

なお、正規表現に以下を設定すると、
'True'上で'+'か'-'を押下で、'FALSE'になり、
'False'上で'+'か'-'を押下で、'true'になり、
以降、'FALSE'、'true'上で'+'か'-'により'FALSE'<->'true'間で切り替えとなりました。

```
  \         {'pattern': 'True', 'replace': 'False'},
  \         {'pattern': 'TRUE', 'replace': 'FALSE'},
```

よい対応方法があれば教えていただけませんでしょうか？
お手数ですが、どうぞよろしくお願いします。

**Comment by syngan** [comment]
問題は, `ignorecase` オプションを指定していることで発生しています。
解決方法としては正規表現指定時に `\C` を設定していただくのが良いと思いますが、その場合の定義方法も正しくありません（ドキュメント不足で申し訳ありません）。
あと、別の問題ですが、関数名は大文字で指定する必要がある(vim scriptの仕様)ので, `g:default_pm` ではなく、 `g:Default_pm` のようにすべきです。

以下のように設定していただくと意図した動作になると思います。

```
  let g:clurin = {'-': {'def': [[
        \ {'pattern': '\CTrue', 'replace': 'True'},
        \ {'pattern': '\CFalse', 'replace': 'False'}], [
        \ {'pattern': '\CTRUE', 'replace': 'TRUE'}, 
        \ {'pattern': '\CFALSE', 'replace': 'FALSE'}]]}}
```

**Comment by syngan** [comment]
コメント後に現在の挙動が変だと思ったので、最初に書いていただいている文字列指定の方法で `ignorecase` オプションが設定されていても動作する(`\C` をつける）ように修正しました。 ご確認ください。

**Comment by lamsh** [comment]
早速のご対応ありがとうございます。
確認しました。望み通りの動作をしていますね。よかったです。

また、関数名のご指摘もありがとうございます。ユーザー関数は先頭を大文字にしないといけないのですね…
`g:`でグローバルにしなくても動作したので、以下のように`s:`でスクリプトローカルにしました（それに付随してnomatchの値の部分も）。

```
  function! s:Default_pm(cnt) abort
```

Vimの切り替えプラグインを探していて、vim-clurinはswitch.vimの欠点を指摘していてよいと思いました。
今後も使わせていただきます。
